name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install build tools
      run: sudo apt-get install -y build-essential
    - name: Build the project
      run: |
        gcc -o my_program main.c
    - name: Archive the build
      run: zip my_program_linux.zip my_program
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_program_linux
        path: my_program_linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install build tools
      run: choco install make
    - name: Build the project
      run: |
        gcc -o my_program.exe main.c
    - name: Archive the build
      run: powershell Compress-Archive my_program.exe my_program_windows.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_program_windows
        path: my_program_windows.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux build
      uses: actions/download-artifact@v3
      with:
        name: my_program_linux
        path: ./dist
    - name: Download Windows build
      uses: actions/download-artifact@v3
      with:
        name: my_program_windows
        path: ./dist
    - name: Create release
      uses: actions/create-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          ./dist/my_program_linux.zip
          ./dist/my_program_windows.zip
