name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the hello_world_main.c
      run: |
        gcc hello_world_main.c -o hello_world

    - name: Archive hello_world binary
      run: |
        zip hello_world.zip hello_world

    - name: Get the current date and time
      id: get_datetime
      run: echo "RELEASE_TAG=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: "Release ${{ env.RELEASE_TAG }}"
        body: "Automatic release from workflow run ${{ github.run_number }}."
        files: hello_world.zip
