name: C Build and Release

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile the program
      run: gcc -o my_program_linux main.c 

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_program_linux
        path: my_program_linux

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        choco install mingw -y

    - name: Compile the program
      run: gcc -o my_program_windows.exe main.c 

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_program_windows
        path: my_program_windows.exe

  tag_and_release:
    needs: [build_linux, build_windows]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Linux artifact
      uses: actions/download-artifact@v2
      with:
        name: my_program_linux
        path: .

    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: my_program_windows
        path: .

    - name: Create tag
      id: create_tag
      run: |
        TAG_NAME=$(date +'%Y%m%d%H%M%S')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./my_program_linux
        asset_name: my_program_linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./my_program_windows.exe
        asset_name: my_program_windows.exe
        asset_content_type: application/octet-stream
